-define(DEFAULT_RETRIES, 0).
-define(DEFAULT_RETRY_TIME, 1000).
-define(DEFAULT_KEEPALIVE_TIMEOUT, 60_000).
-define(DEFAULT_CONNECT_TIMEOUT, 60_000).
-define(DEFAULT_HACKNEY_RECEIVE_TIMEOUT, 120_000).
-define(DEFAULT_HACKNEY_CHECKOUT_TIMEOUT, 8_000).

%% Hackney pool
-define(HACKNEY_POOL, hb_hackney_pool).
-define(DEFAULT_HACKNEY_MAX_CONNECTIONS, 100).
