#!/bin/sh
set -eu

ROOT="${HB_DOCS_TEST_ROOT:-/mnt/atl-83174bc4f5874d/src/hyperbeam-docs-info}"
cd "$ROOT"

EVAL='
application:ensure_all_started(hackney),
Base = (hb_opts:default_message_with_env())#{<<"prometheus">> => false},
KaySigner = <<"kaYP9bJtpqON8Kyy3RbqnqdtDBDUsPTQTNUCvZtKiFI">>,
DeviceSpecs =
    [
        {<<"ans104@1.0">>,
            <<"iGdNvBSxX5SezsNfIhYhU2UDs69MMU4lkGo24GpvziE">>,
            <<"VQpD8DDQMmas_ty8oOtu4c0n3ibcZMZCX5inxGV_kNw">>
        },
        {<<"apply@1.0">>,
            <<"oL40i32nF8zD3AMlVz9RCj6t36Fw08vWnzK9lfuFdBg">>,
            <<"JZ78xROhCK0e3skLilXvNBuu-Gztob2rw9dQDp5YrEo">>
        },
        {<<"b32-name@1.0">>,
            <<"5MgPIPy4_rSXC9YNoJi6OCyWIY_6C-Fp8cl44QcTapU">>,
            <<"gE-bMNllUXKZNLd-isuxBMYw4thWh-KpeEtNqs8IvHI">>
        },
        {<<"cookbook@1.0">>,
            <<"EViNYObPezaj4qC2dFfpp2axlp1GFSo_zjZHdrb64Vw">>,
            <<"Sf9p0YF3yRe-FIsHV1QhdJg3yFEefS7eB5MkgaeIhPk">>
        },
        {<<"dedup@1.0">>,
            <<"BGwSbwWMWAtNwHaA5RaSMp9cMAOrSAY1uZAfvjVkS8Y">>,
            <<"yDNlWvyhCghU1hOJzYCCC3qhyYDhyjbnGxqtxN5Gq_s">>
        },
        {<<"delegated-compute@1.0">>,
            <<"fhG_dHu1nrNX8vqnA4DfTW8MkuzOYq-cCV0QpK55nIw">>,
            <<"SgFtkWrwIX0QwHe6tgvVQ2roqmWfln99hccmUMT4gx4">>
        },
        {<<"flat@1.0">>,
            <<"jlrnaiLa6cwsyUnjWD3YC4qHl0Pic_Q-uK6ZEDmSzzA">>,
            <<"79IKYUygFpOvRkfEQKBep5OEyOLxvzUHqLZxZRXd0Yw">>
        },
        {<<"genesis-wasm@1.0">>,
            <<"L-agwnlODXYMKr1ErSIKxw8h8aqSCq4bgouRJHjzlsQ">>,
            <<"wFEqDKOEekF_4Y0HpZ1yvV8XCTzEvEh34o44cu0qiiI">>
        },
        {<<"gzip@1.0">>,
            <<"TFZJsMZhzyqOHszMX04XEVWzVUgCBv5dK8RLOGwFYQc">>,
            <<"-dQhrwRai9Y5iOGU5TjvzPuNX9q11iEiOUxZxlRh630">>
        },
        {<<"httpsig@1.0">>,
            <<"KZzDPbpfsLhsigKg7TQq5rvSL2MVrorfpwsXzcLZxiQ">>,
            <<"pKaWP1EszlXc0YyOGB35beFv5ldtbXGOl98hnpcd6ZQ">>
        },
        {<<"json@1.0">>,
            <<"qD4k5Jw9J4cb_HBjSl897otUR9iz0pqeXm9H8p0QjCY">>,
            <<"aXspr7YecuiWJdkOS_l1A8ulESutaiMIpmFwwcS5_Cw">>
        },
        {<<"json-iface@1.0">>,
            <<"PvmF4Ndyw39pWnP4nrjzTVkJ00BdsYesoVTfPDIMTE4">>,
            <<"mdnIQ5Q-Y3p_EVsxt9B7Ze7NJWEuypYjRGXwhd3mhNU">>
        },
        {<<"local-name@1.0">>,
            <<"vTIAO564UyCrycqrlTOG0UM9iYjwtL_qkDwPo7_7pr0">>,
            <<"JP1JDMq3cSGcBXJl3TEgSxgByKI55QuGNxCz8yaKvT8">>
        },
        {<<"lua@5.3a">>,
            <<"tnaffVNH8UIOR3rliKGR5Dv7SoNz5S4e-TT55QrFrkA">>,
            <<"oObvcO_S54HEAzt3qGK-M8myY310A6146wGbReAP7fI">>
        },
        {<<"match@1.0">>,
            <<"kOcxgqQWK4SIqN_L7c5HqN-iarYkkJi6-bpLQONOLo8">>,
            <<"vbyiJfcAj0kKBbBK19CKSqQ2yxZ26RYiYd2Dc7LYd1U">>
        },
        {<<"message@1.0">>,
            <<"SmKKa51azSM3KjsNL4A6wAz2Nap3p4RH_PhLJYsDqac">>,
            <<"e8E8f2YMGp5ilOEiH45BBRK3h4al3npx9KrzmG2gxmU">>
        },
        {<<"meta@1.0">>,
            <<"eTTrhnCa2ZqJJWMLANlQcWEAy8AUjhAq1F7d2tHqd2k">>,
            <<"iOuPKXRVFGOeBOi-_sKIy4tlShDaJFGS4U5sA5Ub_8A">>
        },
        {<<"metering@1.0">>,
            <<"BmWAXdD5OUDT8ghp_b6ebkKBdggDXpZk0MxD838ywoQ">>,
            <<"q6kua0WR1tV9KMUXDkCGQpIJ_dPclk5Gw59ebA59gKc">>
        },
        {<<"multipass@1.0">>,
            <<"6J7Hwd2tzlFmEP3GRxQDsPpFpXKnio2k7O4drSAocbo">>,
            <<"7nB-5oIlOP9lB1Q46UmomHJCF-Q4BYSTTGw9kIGjyWY">>
        },
        {<<"name@1.0">>,
            <<"vhC9owh6eabAv8mAOLuBnzZg79bSvSK006pBaObutVg">>,
            <<"zRoBDb_b7P6sTW8vn1bcJiLPSImXQWG6Q32iKqPBrc4">>
        },
        {<<"node-process@1.0">>,
            <<"k9IUjLgloAcuGfCwkEHKPODYnLjtQEx90YV50KsP82U">>,
            <<"WggFMGdRZhSl_YQimd6k3dx90sOkT7gKu-ISqg_MP20">>
        },
        {<<"p4@1.0">>,
            <<"04A3AAPBpXXHZNp0Zypttys5nKnQI6dXHQek3R2fT6s">>,
            <<"21hFzm7km_ApHP3Zc-1sD3FO1YBjhmiSeS1gpRen2TA">>
        },
        {<<"patch@1.0">>,
            <<"7zUfEEv04KQhDqDy8MEZ4wY6PcwZiUcDd11jl23Een8">>,
            <<"Ipa71TKM4i6PphVHV0VOEYPrX1MpI-F0d6BvycfnDPs">>
        },
        {<<"push@1.0">>,
            <<"TGRZ0ckK4s_OMEkeGdT-tvpwlEway0DhE8bymCoui4E">>,
            <<"fqGsjbSZIPtvrfuLC--yaRVeid9DyASj7fx1EN7W8-E">>
        },
        {<<"relay@1.0">>,
            <<"80cPlu3SISx7sKbgLDON-Q9M0eVh-4YQopkLRA6QyyU">>,
            <<"HcnFjYVlN4LD-GgrZ5jkMIlIJEgwReu_Wccvr7rpe6c">>
        },
        {<<"router@1.0">>,
            <<"Qhkx7PE7n4juig_leI8e6woyOOymDeoPH9aoBwtQwWw">>,
            <<"4pAfClJnsLsmUQUhoL89HyzwYDRtHr1kj5xfJOklTQE">>
        },
        {<<"scheduler@1.0">>,
            <<"ttysr6oagLNxsJsibyQY24NkttuxJV1ru5ohiF7sTtM">>,
            <<"SxMDeVg5n6XsnZlPLGkUWvblCib3509u8E-4bbAMaf8">>
        },
        {<<"stack@1.0">>,
            <<"_KYjj30vA6i6Ph8eE0kL5MSqBs89MrVBc21Tti6OF1c">>,
            <<"vaSPhUSxg90MCG7c8at78DgpyPXQ2x5TxGSAJWUHUz8">>
        },
        {<<"structured@1.0">>,
            <<"DZHYmv2RK2Dvf2dm-xmWqbA1RfVrlA37s8NHOgotgcU">>,
            <<"VvAAMVAoFzNzO5kNYM9I2oolPfTHpCsmx-v8zlpwMSs">>
        },
        {<<"trie@1.0">>,
            <<"HJQuA_b_Hasj9hMYzXDZ85twvl-3V32kJH4Y_M80U3Q">>,
            <<"MK4_sYJQ8lrK6iFIzH0hkRcQ-3Johxi472kVK-DPU4g">>
        },
        {<<"tx@1.0">>,
            <<"EGeMK0kY9xbJG1eet5jsQaDOljAt3TlE8ZXU70ZvCjM">>,
            <<"ugf2p5v908SggTh0P-kJRQqDCxM-FoO-GZb3760dYO0">>
        },
        {<<"wasi@1.0">>,
            <<"i9dNb_cNrCqMqvKIi36a6g-ag6wn_mtxvX_UFYnjILI">>,
            <<"AQ8GZfyFXxnTVAsq-3pIHZbb9go_mxd3P1ts9mlWtsA">>
        },
        {<<"wasm-64@1.0">>,
            <<"Pn_6a0Q9Ft-K29CYiI5jcYlKe-EoD4_N_vHqSl328gU">>,
            <<"gYh0h-LbluO154cO5zHy2KrJ9cX6fF87ACKrLPojEFk">>
        }
    ],
NameResolvers =
    [
        maps:from_list([
            {Device, Spec}
        || {Device, Spec, _Impl} <- DeviceSpecs
        ])
        | hb_opts:get(<<"name-resolvers">>, [], Base)
    ],
TrustedDevices =
    maps:merge(
        hb_opts:get(<<"trusted-devices">>, #{}, Base),
        maps:from_list([
            {Spec, Impl}
        || {_Device, Spec, Impl} <- DeviceSpecs
        ])
    ),
TrustedSigners =
    [
        #{
            <<"address">> => KaySigner,
            <<"devices">> =>
                lists:flatmap(
                    fun({Device, Spec, _Impl}) -> [Device, Spec] end,
                    DeviceSpecs
                )
        }
    ] ++ [
        Signer
    || Signer <- hb_opts:get(<<"trusted-device-signers">>, [], Base)
    ],
DocsFixtureProcessID = <<"co-MIhejkMR8v3-oIvW8m_u3YfV7zXoII0ja1wk-IOo">>,
DocsFixtureNode =
    unicode:characters_to_binary(
        os:getenv("HB_DOCS_PROCESS_FIXTURE_NODE", "")
    ),
DocsFixtureScheduler =
    unicode:characters_to_binary(
        os:getenv(
            "HB_DOCS_PROCESS_FIXTURE_SCHEDULER",
            "YUsEnCSlxvOMxRd1qG6rkaPwMgi3xOorfDfYJoMDndA"
        )
    ),
DocsFixtureRoutes =
    case DocsFixtureNode of
        <<>> ->
            [];
        _ ->
            [
                #{
                    <<"template">> =>
                        <<"^/", DocsFixtureProcessID/binary,
                            "~(process|scheduler)@1\\.0(/.*|$)">>,
                    <<"strategy">> => <<"Nearest">>,
                    <<"nodes">> => [
                        #{
                            <<"wallet">> => DocsFixtureScheduler,
                            <<"prefix">> => DocsFixtureNode
                        }
                    ]
                }
            ]
    end,
Opts =
    Base#{
        <<"port">> => 28737,
        <<"node-host">> => <<"docs-test.mystical.computer">>,
        <<"prometheus">> => false,
        <<"system-monitor">> => false,
        <<"process-sampler">> => false,
        <<"load-remote-devices">> => true,
        <<"name-resolvers">> => NameResolvers,
        <<"trusted-devices">> => TrustedDevices,
        <<"trusted-device-signers">> => TrustedSigners,
        <<"routes">> => DocsFixtureRoutes ++ hb_opts:get(<<"routes">>, [], Base),
        <<"on">> => maps:merge(hb_opts:get(<<"on">>, #{}, Base), #{
            <<"request">> => #{
                <<"device">> => <<"router@1.0">>,
                <<"path">> => <<"preprocess">>,
                <<"commit-request">> => true
            }
        }),
        <<"docs-recipe-blacklist-file">> => <<"config/docs-test-recipe-blacklist.json">>
    },
Url = hb_http_server:start_node(Opts),
io:format("started ~s~n", [Url]),
receive after infinity -> ok end.
'

exec /usr/bin/erl +S 2:2 +A 2 -pa _build/default/lib/*/ebin -noshell -eval "$EVAL"
